# Generated by Django 5.1.6 on 2025-06-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_quantity', models.IntegerField(default=0)),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_histories', to='surplus.surplusitem')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
