# Generated by Django 5.1.6 on 2025-06-10 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0002_pickuphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuphistory',
            name='picked_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pickuphistory',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
