# Generated by Django 5.1.6 on 2025-06-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0003_alter_pickuphistory_picked_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusitem',
            name='original_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
