# Generated by Django 5.1.6 on 2025-06-10 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0004_surplusitem_original_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusitem',
            name='donator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='surplus_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
