# Generated by Django 5.1.6 on 2025-06-10 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0005_surplusitem_donator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surplusitem',
            name='donator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surplusitem',
            name='original_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
